rbac:
  enabled: false
#--------------------------------------------------------
kibana:
  name: kibana
  replicaCount: 1
  image:
    repository: docker.elastic.co/kibana/kibana-oss
    tag: 6.7.0
    pullPolicy: IfNotPresent
  env:
    ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    SERVER_PORT: 5601
    SERVER_DEFAULTROUTE: "/app/kibana"
  files:
    kibana.yml:
      server.name: kibana
      server.host: "0"
      elasticsearch.hosts: http://elasticsearch:9200
  service:
    type: ClusterIP
    port: 5601
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - kibana.dev
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
#--------------------------------------------------------
elasticsearch:
  name: elasticsearch
  replicaCount: 1
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 6.2.4
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9200
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
#--------------------------------------------------------
fluent_bit:
  name: fluent_bit
  image:
    repository: fluent/fluent-bit
    tag: 1.3.7
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  dockerContainersPath: /var/lib/docker/containers
  service:
    type: ClusterIP
    port: 2020
    labels: {}
    # nodePort: 30020
    annotations: {}
  #   prometheus.io/path: "/api/v1/metrics/prometheus"
  #   prometheus.io/port: "2020"
  #   prometheus.io/scrape: "true"

## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush 1
          Log_Level {{ .Values.fluent_bit.logLevel }}
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.fluent_bit.service.port }}
          Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On
 
      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On

  ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On

  ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          Name es
          Match kube.*
          Host elasticsearch-master
          Logstash_Format On
          Retry_Limit False

      [OUTPUT]
          Name es
          Match host.*
          Host elasticsearch-master
          Logstash_Format On
          Logstash_Prefix node
          Retry_Limit False

  ## https://docs.fluentbit.io/manual/pipeline/parsers
    customParsers: |
      [PARSER]
          Name docker_no_time
          Format json
          Time_Keep Off
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%L

  # This allows adding more files with arbitary filenames to /fluent-bit/etc by providing key/value pairs.
  # The key becomes the filename, the value becomes the file content.
    extraFiles: {}
  #     example.conf: |
  #       [OUTPUT]
  #           Name example
  #           Match foo.*
  #           Host bar

# The config volume is mounted by default, either to the existingConfigMap value, or the default of "fluent-bit.fullname"

  volumeMounts:
    - name: config
      mountPath: /fluent-bit/etc/fluent-bit.conf
      subPath: fluent-bit.conf
    - name: config
      mountPath: /fluent-bit/etc/custom_parsers.conf
      subPath: custom_parsers.conf

  daemonSetVolumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
    - name: etcmachineid
      hostPath:
        path: /etc/machine-id
        type: File

  daemonSetVolumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
    - name: etcmachineid
      mountPath: /etc/machine-id
      readOnly: true

  loglevel: info
