---

- name: Install common packages
  apt:
    name:
      - less
      - locales
      - sysstat
      - jq
      - python-setuptools
      - python-pip
      - htop
      - ncdu
      - vim
      - dnsutils
      - iputils-ping
      - netcat
      - bash-completion
      - tcpdump
      - strace
      - locales
    update_cache: yes
  tags:
    - common
    - packages

- name: Ensure TCP keepalive is 120 sec
  sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: "120"
    sysctl_set: yes
  become: true
  tags:
    - common
    - keepalive

- name: "sysctl: net.core.somaxconn"
  sysctl:
    name: net.core.somaxconn
    value: "4098"
    sysctl_set: yes
  become: true

- name: "sysctl: net.core.netdev_max_backlog"
  sysctl:
    name: net.core.netdev_max_backlog
    value: "16384"
    sysctl_set: yes
  become: true

- name: "sysctl: net.core.rmem_max"
  sysctl:
    name: net.core.rmem_max
    value: "16777216"
    sysctl_set: yes
  become: true

- name: "sysctl: net.core.wmem_max"
  sysctl:
    name: net.core.wmem_max
    value: "16777216"
    sysctl_set: yes
  become: true

- name: "sysctl: net.ipv4.tcp_wmem"
  sysctl:
    name: net.ipv4.tcp_wmem
    value: "4096 12582912 16777216"
    sysctl_set: yes
  become: true

- name: "sysctl: net.core.wmem_max"
  sysctl:
    name: net.ipv4.tcp_rmem
    value: "4096 12582912 16777216"
    sysctl_set: yes
  become: true

- name: "sysctl: net.ipv4.tcp_max_syn_backlog"
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: "16192"
    sysctl_set: yes
  become: true

#https://github.com/ton31337/tools/wiki/tcp_slow_start_after_idle---tcp_no_metrics_save-performance
- name: "sysctl: net.ipv4.tcp_slow_start_after_idle"
  sysctl:
    name: net.ipv4.tcp_slow_start_after_idle
    value: "0"
    sysctl_set: yes
  become: true

- name: "sysctl: net.ipv4.tcp_tw_reuse"
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: "1"
    sysctl_set: yes
  become: true

- name: "sysctl: net.ipv4.ip_local_port_range"
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: "10240 65535"
    sysctl_set: yes
  become: true

- name: Generate locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - en_US.UTF-8
    - ru_RU.UTF-8
  tags:
    - common
    - locales
