---
- name: Deploy kibana
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yml.j2') | from_yaml }}"
    state: present
    context: "{{ k8s_cluster_env[cluster_env] }}"
    namespace: infra
  loop:
    - deployment
    - service
